name: indagram
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_core: ^2.14.0
  google_sign_in: ^6.1.4
  font_awesome_flutter: ^10.5.0
  google_sign_in_web: ^0.12.0+2
  hooks_riverpod: ^2.3.6
  uuid: ^3.0.7
  image_picker: ^1.0.0
  image: ^4.0.17
  firebase_storage: ^11.2.4
  flutter_hooks: ^0.18.6
  collection: ^1.17.1
  intl: ^0.18.1
  video_thumbnail: ^0.5.3
  video_player: ^2.7.0
  lottie: ^2.4.0
  share_plus: ^7.0.2
  url_launcher: ^6.1.12
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.1
  build_test: ^2.1.7
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/animations/empty.json
  - assets/animations/loading.json
  - assets/animations/data_not_found.json
  - assets/animations/error.json
  - assets/animations/small_error.json
  
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
