// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKGSleZ8szt3Kphdi_wNmEVxGjZryB6Fw',
    appId: '1:959481423573:web:ac7eada7511f873759e45c',
    messagingSenderId: '959481423573',
    projectId: 'indagram-e5443',
    authDomain: 'indagram-e5443.firebaseapp.com',
    storageBucket: 'indagram-e5443.appspot.com',
    measurementId: 'G-VDR1HP6B8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnYruAHXfvubkiVKDUaamvNzQ8X-i2myo',
    appId: '1:959481423573:android:5f00aaf89904b55659e45c',
    messagingSenderId: '959481423573',
    projectId: 'indagram-e5443',
    storageBucket: 'indagram-e5443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBieR21RTEDBOxAEoTMOhvgCfBt51PjFW0',
    appId: '1:959481423573:ios:9adc0dda8548c48659e45c',
    messagingSenderId: '959481423573',
    projectId: 'indagram-e5443',
    storageBucket: 'indagram-e5443.appspot.com',
    iosClientId: '959481423573-8teh1120jjpkrf45rqdisejfghbcp3ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.indagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBieR21RTEDBOxAEoTMOhvgCfBt51PjFW0',
    appId: '1:959481423573:ios:62aa578b0e77d30359e45c',
    messagingSenderId: '959481423573',
    projectId: 'indagram-e5443',
    storageBucket: 'indagram-e5443.appspot.com',
    iosClientId: '959481423573-tnte469qjhkc0pouil3udiinibqib9jc.apps.googleusercontent.com',
    iosBundleId: 'com.example.indagram.RunnerTests',
  );
}
